version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URI: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["bash", "wait-for-db.sh"]

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
